# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'labo_atte' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for labo_atte
  pod 'R.swift'

  target 'labo_atteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'labo_atteUITests' do
    # Pods for testing
  end

end
